package springbook.user.dao;

import java.sql.SQLException;

import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.GenericXmlApplicationContext;

import springbook.user.domian.User;

public class UserDaoTest {
	
	@Test
	public void addAndGet() throws SQLException {
	
		//ApplicationContext context = new AnnotationConfigApplicationContext(DaoFactory.class);
		ApplicationContext context = new GenericXmlApplicationContext("applicationContext.xml");
		UserDao dao = context.getBean("userDao",UserDao.class);
		
		User user = new User();
		user.setId("tello");
		user.setName("이진우");
		user.setPassword("q1w2e3r4");
		
		dao.add(user);
		
		System.out.println(user.getId() + " 등록 성공");
		
		User user2 = dao.get(user.getId());
		
		if(!user.getName().equals(user2.getName()))
			System.out.println("테스트 실패 (name)");
		else if(!user.getPassword().equals(user2.getPassword()))
			System.out.println("테스트 실패(password)");
		else
			System.out.println("조회 테스트 성공");

	}

}
